name: XeonSuiteWarp
version: ${project.version}
description: Warpplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.warp.Warpplugin
load: POSTWORLD
depend: [XeonSuiteBukkit]


commands:
  setwarp:
    description: Set a Warp.
  warp:
    description: Teleport to a Warp.
    aliases: [warpto, w]
  warps:
    description: Get Warplist.
  delwarp:
    description: Delete a Warp
permissions:
    xeonSuite.warp.team:
        description: Alle Team Permissions
        children:
            xeonSuite.warp.user: true
            xeonSuite.warp.setwarp: true
            xeonSuite.warp.delwarp: true
    xeonSuite.warp.user:
        description: Alle User Permissions
        children:
            xeonSuite.warp.warp: true
            xeonSuite.warp.warps: true
    xeonSuite.warp.warp:
        description: Teleport to warp
        default: op
    xeonSuite.warp.setwarp:
        description: Set warp
        default: op
    xeonSuite.warp.warps:
        description: Warplist
        default: op
    xeonSuite.warp.delwarp:
        description: Delwarp
        default: op
