name: MineSuiteWarp
version: ${project.version}
description: MineSuiteWarp Plugin
authors: [Kekshaus]
main: de.linzn.mineSuite.warp.WarpPlugin
load: POSTWORLD
depend: [MineSuiteCore]


commands:
  setwarp:
    description: Set a Warp.
  warp:
    description: Teleport to a Warp.
    aliases: [warpto, w]
  warps:
    description: Get Warplist.
  delwarp:
    description: Delete a Warp
permissions:
    mineSuite.warp.team:
        description: Alle Team Permissions
        children:
            mineSuite.warp.user: true
            mineSuite.warp.setwarp: true
            mineSuite.warp.delwarp: true
    mineSuite.warp.user:
        description: Alle User Permissions
        children:
            mineSuite.warp.warp: true
            mineSuite.warp.warps: true
    mineSuite.warp.warp:
        description: Teleport to warp
        default: op
    mineSuite.warp.setwarp:
        description: Set warp
        default: op
    mineSuite.warp.warps:
        description: Warplist
        default: op
    mineSuite.warp.delwarp:
        description: Delwarp
        default: op
